config/routes.rb
DishManage::Application.routes.draw do
  resources :apks
  get 'download' => 'apks#download'

end

app/models/apk.rb
# encoding: utf-8

class Apk < ActiveRecord::Base
  attr_accessible :location, :update_items, :vc, :vn, :apkfile
  attr_accessor :apkfile

  validates_presence_of :update_items, :vn, :vc
	validate :check_vc_and_vn

  before_create :save_apk_to_file
  private
  def save_apk_to_file
    origname = apkfile.original_filename
    basename = File.basename(origname,".*")
    extname = File.extname(origname)
    endname = basename  + '_' + vn + '_' + vc + extname
    location = '/swidy/client/' + endname
    write_attribute :location, location
    File.open(Rails.root.join('/swidy/client', '', endname), 'wb') do |file|
    file.write(apkfile.read)
    end
		ver_info = {:vc => vc, :vn => vn, :update_items => update_items}
				File.open '/swidy/client/update.json','w+' do |file|
				file.write ver_info.to_json
		end
  end 

	def check_vc_and_vn
  if Apk.find_by_vc_and_vn(vc,vn) then
		errors.add(:vn, "版本已存在") 
		errors.add(:vc, "版本已存在") 
		end
	end
end

app/controllers/apks_controller.rb
class ApksController < ApplicationController
  # GET /apks
  # GET /apks.json
  def index
    @apks = Apk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apks }
    end
  end

	def download
	send_file params[:id]
	end
  # GET /apks/1
  # GET /apks/1.json
  def show
    @apk = Apk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apk }
    end
  end

  # GET /apks/new
  # GET /apks/new.json
  def new
    @apk = Apk.new
  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apk }
    end
  end

  # GET /apks/1/edit
  def edit
    @apk = Apk.find(params[:id])
  end

  # POST /apks
  # POST /apks.json
  def create
    @apk = Apk.new(params[:apk])
    test = @apk.save
    respond_to do |format|
      if test
        format.html { redirect_to @apk, notice: 'Apk was successfully created.' }
        format.json { render json: @apk, status: :created, location: @apk }
      else
        format.html { render action: "new" }
        format.json { render json: @apk.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /apks/1
  # PUT /apks/1.json
  def update
    @apk = Apk.find(params[:id])

    respond_to do |format|
      if @apk.update_attributes(params[:apk])
        format.html { redirect_to @apk, notice: 'Apk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apks/1
  # DELETE /apks/1.json
  def destroy
    @apk = Apk.find(params[:id])
    @apk.destroy

    respond_to do |format|
      format.html { redirect_to apks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/apks_helper.rb
module ApksHelper
end

app/views/apks/_form.html.erb
<%= form_for(@apk) do |f| %>
  <% if @apk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apk.errors.count, "error") %> prohibited this apk from being saved:</h2>

      <ul>
      <% @apk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :安卓客户端 %><br />
    <%= f.file_field :apkfile %>
  </div>
  <div class="field">
    <%= f.label :版本编号 %><br />
    <%= f.text_field :vc %>
  </div>
  <div class="field">
    <%= f.label :版本号 %><br />
    <%= f.text_field :vn %>
  </div>
  <div class="field">
    <%= f.label :更新信息 %><br />
    <%= f.text_area :update_items %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apks/edit.html.erb
<h1>Editing apk</h1>

<%= render 'form' %>

<%= link_to 'Show', @apk %> |
<%= link_to 'Back', apks_path %>

app/views/apks/index.html.erb
<h1>客户端列表</h1>

<table>
  <tr>
    <th>版本编号</th>
    <th>版本号</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apks.each do |apk| %>
  <tr>
    <td><%= apk.vc %></td>
    <td><%= apk.vn %></td>
    <td><%= link_to 'Show', apk %></td>
    <td><%= link_to 'download', :controller => "apks", :action => "download", :id => apk.location %></td>
    <td><%= link_to 'Edit', edit_apk_path(apk) %></td>
    <td><%= link_to 'Destroy', apk, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '上传APK', new_apk_path %>

app/views/apks/new.html.erb
<h1>上传APK</h1>

<%= render 'form' %>

<%= link_to '返回', apks_path %>

app/views/apks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>版本编号:</b>
  <%= @apk.vc %>
</p>

<p>
  <b>版本号:</b>
  <%= @apk.vn %>
</p>

<p>
  <b>更新信息:</b>
  <%= @apk.update_items %>
</p>

<p>
  <b>路径:</b>
  <%= @apk.location %>
</p>


<%= link_to 'download', :controller => "apks", :action => "download", :id => @apk.location %> |
<%= link_to 'Edit', edit_apk_path(@apk) %> |
<%= link_to 'Back', apks_path %>